language: node_js
node_js:
  - 6
install:
  - yarn
  - yarn run bootstrap
script:
  - yarn run test-ci
env:
  global:
    - USE_YARN=yes
addons:
  code_climate:
    repo_token: CODE-CLIMATE-TOKEN
after_success:
  - npm install -g codeclimate-test-reporter netlify-cli
  - codeclimate-test-reporter < coverage/lcov.info
  - 'if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then netlify deploy -e production -t NETLIFY-TOKEN -s NETLIFY-SITE-ID; fi'