language: node_js
node_js:
  - 6
cache:
  yarn: true
install:
  - yarn
script:
  - yarn test
env:
  global:
    - USE_YARN=yes
addons:
  code_climate:
    repo_token: 194c145c5ab13ed3aee5d3274d56427e6809b591ca03531645f9796dfa365bb7